# Generated by Django 6.0.5 on 2026-05-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('identity_document', 'Identity Document'), ('employment_contract', 'Employment Contract'), ('payslip', 'Payslip'), ('invoice', 'Invoice'), ('tax_form', 'Tax Form'), ('other', 'Other')], default='other', max_length=50)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20)),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True)),
                ('raw_text_preview', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
